variables:
  MYSQL_DATABASE: "z_for_test"
  MYSQL_ROOT_PASSWORD: "mysql"

stages:
  - test1
  - deploy

.test1_template: &test1_template
  services:
    - mysql:5.7.22
  script:
    - php -v
    - composer selfupdate --no-progress
    - composer -V
    - composer install --no-interaction --no-progress --no-suggest --optimize-autoloader
    - cp tests/_helpers/mysqlGL.neon tests/tests.local.neon
    - mkdir coverage/
    - mkdir tests/_temp
    - src/run-tests --bootstrap tests/bootstrap.php -s -p php --colors 1 --coverage coverage/coverageGL.html --coverage-src src/ tests/
  after_script:
    - for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
  cache:
    paths:
      - vendor/
  coverage: '/\d+\% covered/'
  artifacts:
    paths:
      - coverage/
    expire_in: 1 hrs
  except:
    - tags

test:7.3:
  image: iao2/docker-php-ci2:7.3
  stage: test1
  <<: *test1_template

pages:
  stage: deploy
  script:
    - mv coverage/ public/
  dependencies:
    - test:7.3
  artifacts:
    paths:
    - public
    expire_in: 30 days
  only:
    - master
  except:
    - tags
